#!/bin/sh
set -e

# make folders
mkdir -p \
    /config/{keys,www} \
    /config/log/nginx \
    /config/nginx/site-confs \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx

# permissions
chown -R nginx:nginx \
    /var/lib/nginx \
    /var/tmp/nginx

chown -R nginx:nginx \
    /config/keys \
    /config/log \
    /config/nginx

chown nginx:nginx \
    /config/www

chmod -R g+w \
    /config/nginx

chmod -R 644 /etc/logrotate.d

if [[ -f "/config/log/logrotate.status" ]]; then
    chmod 600 /config/log/logrotate.status
fi

# remove old samples
find /config/nginx/ \
    -name "*.conf.sample" \
    -type f \
    -delete

# copy new samples
find /defaults/nginx/ \
    -maxdepth 1 \
    -name "*.conf.sample" \
    -type f \
    -exec cp "{}" /config/nginx/ \;

find /defaults/nginx/site-confs/ \
    -maxdepth 1 \
    -name "*.conf.sample" \
    -type f \
    -exec cp "{}" /config/nginx/site-confs/ \;

# first arg is `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- nginx "$@"
fi

# allow the container to be started with `--user`
if [ "$(id -u)" = '0' ]; then
    find . \! -user nginx -exec chown nginx '{}' +
    exec su-exec nginx "$0" "$@"
fi

exec "$@"
